//! Embeds the `Include/*.h` definition files into the WASM binary.
//!
//! A browser has no filesystem and no executable-relative path to search, so
//! the standard macro files — which songs pull in with `Include(...)` — have
//! to travel inside the module. They are embedded as bytes, not text: the
//! files are UTF-8, but the compiler still auto-detects encoding when it
//! reads an include, so a page can register a CP932 file at runtime too.
//!
//! Every `*.h` file under `Include/` is embedded. Non-MML files in that
//! directory (`command2.txt`, `make-command2.hmw`, `memo/`) are build
//! documentation, not `Include`-able macros, and are skipped.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    // This crate is only ever built from a full checkout of the repository
    // (via `wasm-pack`, not a standalone `cargo publish`), so `Include/` at
    // the repository root is always reachable. Fail loudly rather than
    // silently shipping a WASM binary with no embedded includes if that
    // assumption ever breaks.
    let include_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../Include")
        .canonicalize()
        .unwrap_or_else(|err| {
            panic!(
                "sakuramml-wasm build.rs: could not find the repository's Include/ \
                 directory at {}: {err}. This crate must be built from a full \
                 checkout of https://github.com/kujirahand/sakuramml.",
                PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                    .join("../../../Include")
                    .display()
            )
        });

    println!("cargo:rerun-if-changed={}", include_dir.display());

    let mut files: Vec<PathBuf> = std::fs::read_dir(&include_dir)
        .unwrap_or_else(|err| panic!("reading {}: {err}", include_dir.display()))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "h"))
        .collect();
    files.sort();

    assert!(
        !files.is_empty(),
        "sakuramml-wasm build.rs: found no *.h files under {}",
        include_dir.display()
    );

    let mut generated = String::from(
        "// Generated by build.rs — the Include/*.h files, embedded.\n\
         pub static EMBEDDED_INCLUDES: &[(&str, &[u8])] = &[\n",
    );
    for path in &files {
        let name = path.file_name().unwrap_or_default().to_string_lossy();
        println!("cargo:rerun-if-changed={}", path.display());
        let _ = writeln!(
            generated,
            "    ({name:?}, include_bytes!({:?})),",
            path.display().to_string()
        );
    }
    generated.push_str("];\n");

    let out =
        Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is set")).join("embedded_includes.rs");
    std::fs::write(&out, generated).expect("write embedded_includes.rs");
}
