//! Embeds the standard definition file into the WASM binary.
//!
//! A browser has no filesystem and no executable-relative path to search, so
//! `stdmsg.h` — which the compiler loads before every song — has to travel
//! inside the module. It is embedded as bytes, not text: the file is CP932 and
//! the compiler detects that when it reads it.
//!
//! Only `stdmsg.h` is embedded (7 KB). Embedding all of `Include/` would add
//! 600 KB to a 170 KB binary, so the rest are supplied at runtime through
//! `addInclude()` by pages that need them.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let include_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../Include")
        .canonicalize()
        .unwrap_or_else(|_| PathBuf::from("../../../Include"));

    println!("cargo:rerun-if-changed={}", include_dir.display());

    /// Files small enough, and central enough, to always carry along.
    const EMBED: &[&str] = &["stdmsg.h"];

    let files: Vec<PathBuf> = EMBED
        .iter()
        .map(|name| include_dir.join(name))
        .filter(|path| path.exists())
        .collect();

    let mut generated = String::from(
        "// Generated by build.rs — the Include/*.h files, embedded.\n\
         pub static EMBEDDED_INCLUDES: &[(&str, &[u8])] = &[\n",
    );
    for path in &files {
        let name = path.file_name().unwrap_or_default().to_string_lossy();
        println!("cargo:rerun-if-changed={}", path.display());
        let _ = writeln!(
            generated,
            "    ({name:?}, include_bytes!({:?})),",
            path.display().to_string()
        );
    }
    generated.push_str("];\n");

    let out =
        Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is set")).join("embedded_includes.rs");
    std::fs::write(&out, generated).expect("write embedded_includes.rs");
}
